export const stops = [
 {name:'Cell membrane',place:'The city gate',color:'#5b9e86',icon:'gate',x:0,z:8,heading:'Let it in!',line:'Welcome, explorers! I surround the cell and regulate what enters and leaves. Help me check these visitors.',fact:'The cell membrane is selectively permeable. Different substances cross in different ways; it cannot block every harmful substance.',prompt:'In our simplified checkpoint, let useful visitors in and stop the harmful substance.',type:'gate',items:['Water','Nutrient','Harmful substance','Oxygen'],answers:[1,1,0,1]},
 {name:'Chloroplast',place:'The sunlit garden',color:'#7aab49',icon:'leaf',x:-7,z:4,heading:'Make the food!',line:'A garden that makes its own food? I use light energy, water and carbon dioxide to make sugars through photosynthesis.',fact:'Chloroplasts carry out photosynthesis in plants and algae. Oxygen is released as a product.',prompt:'Choose the three inputs for photosynthesis.',type:'select',items:['Sunlight','Water','Carbon dioxide','Plastic','Salt'],answers:[0,1,2]},
 {name:'Golgi apparatus',place:'The post office',color:'#db9273',icon:'box',x:-8,z:-2,heading:'Special delivery',line:'Packages everywhere! I modify, sort and package proteins and other materials for their destinations.',fact:'The Golgi apparatus modifies and sorts materials, then packages them into vesicles for transport.',prompt:'Read each label and send the package to its destination.',type:'sort',items:['Membrane protein','Stored material','Secreted protein'],choices:['Cell membrane','Storage','Outside the cell'],answers:[0,1,2]},
 {name:'Endoplasmic reticulum',place:'The road network',color:'#d3ab57',icon:'route',x:-3,z:-5,heading:'Follow the network',line:'Follow these winding pathways! My membranes help make and transport materials. Rough ER has ribosomes; smooth ER makes lipids.',fact:'The ER is a membrane network, not literal roads. Rough ER helps process proteins; smooth ER synthesizes lipids and has other roles.',prompt:'Follow a secreted protein: choose each stop in the correct order.',type:'sequence',items:['Golgi apparatus','Transport vesicle','Rough ER'],answers:[2,1,0]},
 {name:'Ribosomes',place:'The protein workshop',color:'#bc8665',icon:'protein',x:3,z:-6,heading:'Build a protein',line:'Cluck, cluck… that is our workshop bell! We are tiny ribosomes. We join amino acids to build proteins, following genetic instructions.',fact:'Ribosomes assemble amino acids into proteins. Dietary protein is digested into amino acids; food itself is not assembled by ribosomes.',prompt:'Follow this model instruction: amino acid A → B → C. Tap the pieces in order.',type:'sequence',items:['Amino acid C','Amino acid A','Amino acid B'],answers:[1,2,0]},
 {name:'Mitochondria',place:'The power station',color:'#d69345',icon:'bolt',x:8,z:-3,heading:'Power the city',line:'The lights are fading! I transfer energy from food into ATP, a usable energy supply for cellular work.',fact:'Mitochondria produce most ATP during aerobic respiration, using products of glucose breakdown and oxygen. Plant cells have mitochondria too.',prompt:'Choose the two supplies used in aerobic respiration.',type:'select',items:['Glucose (food)','Oxygen','Sunlight','Plastic'],answers:[0,1]},
 {name:'Vacuole',place:'The storage reservoir',color:'#65aabe',icon:'drop',x:7,z:4,heading:'Store it!',line:'Welcome to the reservoir! I store water and other substances. In plant cells, my water pressure helps keep the cell firm.',fact:'A plant cell’s large central vacuole stores substances and maintains turgor pressure. It also has digestive and recycling roles.',prompt:'Place each delivery in its labelled storage area.',type:'sort',items:['Water delivery','Nutrient delivery','Waste delivery'],choices:['Water store','Nutrient store','Waste store'],answers:[0,1,2]},
 {name:'Lysosomes',place:'The recycling centre',color:'#9a91bd',icon:'recycle',x:3,z:6,heading:'Clean the city',line:'We contain digestive enzymes that break down unwanted materials. Help our recycling team find what needs to go!',fact:'Lysosomes are characteristic of animal cells. In plants, lytic vacuoles do much of this work. Cell City combines plant and animal examples.',prompt:'Choose the two materials that need to be broken down.',type:'select',items:['Damaged cell parts','Old cellular waste','Healthy ribosome','Useful new protein'],answers:[0,1]},
 {name:'Nucleus',place:'The control centre',color:'#9583b3',icon:'dna',x:0,z:0,heading:'Meet the control centre',line:'You made it! I contain DNA: genetic instructions that direct many cell activities. Every department works together to keep the cell alive.',fact:'The nucleus contains most of a eukaryotic cell’s DNA. Gene expression helps direct protein production and many cell activities.',prompt:'What does the nucleus contain to help direct cell activities?',type:'select',items:['Genetic material (DNA)','Sunlight','Finished food packages'],answers:[0]}
];
export const emergencies=[['The city has no energy.','Mitochondria',5],['Packages are piling up!','Golgi apparatus',2],['Protein production has stopped.','Ribosomes',4],['The entry checkpoint has failed.','Cell membrane',0],['Old cell parts need breaking down.','Lysosomes',7],['Photosynthesis has stopped.','Chloroplast',1]];
