import './style.css';
import './immersive.css';
import { cast, prologue, conversations, travelLines } from './story.js';
import { createCity } from './scene.js';
import { stops, emergencies } from './data.js';
const paths={leaf:'M19 4C8 3 3 8 5 15s15 7 14-11ZM5 20 16 8',gate:'M4 21V6h16v15M8 6V3h8v3M9 10v11m6-11v11',box:'m3 7 9-4 9 4-9 4-9-4Zm0 0v10l9 4 9-4V7M12 11v10M7 5l10 4',route:'M5 4v12a4 4 0 0 0 8 0V8a4 4 0 0 1 8 0v12M2 7l3-3 3 3',protein:'M5 6h3v3H5zm11 9h3v3h-3zM8 8l8 8M16 5h3v3h-3zM5 16h3v3H5zM8 16l8-8',bolt:'m13 2-9 12h7l-1 8 10-13h-8z',drop:'M12 2C9 7 5 11 5 15a7 7 0 0 0 14 0c0-4-4-8-7-13Z',recycle:'m8 4 4-2 4 7M16 5v4h-4M20 12l2 4-8 4m4 1-4-1 1-4M9 20H4l-2-8m-1 4 1-4 4 1',dna:'M7 2c0 10 10 10 10 20M17 2C17 12 7 12 7 22M8 5h8M8 19h8M10 9h4m-4 6h4',map:'m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5Zm6-2v16m6-14v16',book:'M12 6C8 3 5 3 2 4v15c4-1 7 0 10 2 3-2 6-3 10-2V4c-3-1-6-1-10 2Zm0 0v15',star:'m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z',arrow:'M4 12h15m-6-6 6 6-6 6',sound:'M11 4 5 9H2v6h3l6 5V4Zm4 4c3 2 3 6 0 8m3-11c5 4 5 10 0 14',check:'m5 12 4 4L19 6',close:'m6 6 12 12M6 18 18 6',home:'m3 11 9-8 9 8M5 10v11h14V10M9 21v-7h6v7',compass:'m16 8-3 5-5 3 3-5 5-3ZM12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20'};
export const icon=(name,size=20)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.star}"/></svg>`;
let saved;try{saved=JSON.parse(localStorage.getItem('cell-city-v1'));}catch{}
let state={done:Math.min(9,Math.max(0,Number(saved?.done)||0)),stars:Math.max(0,Number(saved?.stars)||0),rescued:saved?.rescued===true,finished:saved?.finished===true};
let active=Math.min(state.done,8),started=false,challenge=null,selected=[],step=0,mistakes=0,sound=false,modalReturn=null;
const $=s=>document.querySelector(s);
let storyLines=[],storyIndex=0,storyComplete=null,nearby=-1,mapOpen=false,lastStatus=null;
$('#app').innerHTML=`<header class="game-header"><a class="brand" href="#" aria-label="Cell City"><span class="brand-icon">${icon('leaf',24)}</span><span>CELL CITY<small>THE SECRET WITHIN</small></span></a><div class="expedition-label">AN EXTRAORDINARY FIELD TRIP</div><nav><button class="nav" id="explore">${icon('map',18)} City map <kbd>M</kbd></button><button class="nav" id="journal">${icon('book',18)} Journal <span id="journal-count">0</span></button><button class="icon-button" id="sound" aria-label="Turn narration on" title="Spoken narration">${icon('sound')}</button><button class="icon-button" id="fullscreen" aria-label="Enter fullscreen" title="Fullscreen">⛶</button></nav></header>
<main><aside class="sidebar" hidden><div class="eyebrow">YOUR FIELD TRIP</div><h1>Follow the<br><em>discovery trail.</em></h1><p class="intro">Choose a discovered stop to walk back with your class.</p><div class="progress-label"><span>Your discoveries</span><b id="progress-text"></b></div><div class="progress"><i id="progress-bar"></i></div><div id="journey" class="journey"></div><button class="text-button" id="close-map">Back to walking</button></aside>
<section class="adventure" aria-label="Walk through Cell City"><div id="world"></div><div id="labels"></div><div class="vignette"></div>
<div class="objective"><div class="objective-icon">${icon('compass',22)}</div><div><span id="objective-kicker">THE MYSTERIOUS FIELD TRIP</span><strong id="destination">Meet your class at the city gates</strong><small id="travel-status">Dr. Maya & four curious explorers</small></div><button id="guide" title="Walk with the teacher" hidden>Follow teacher ${icon('arrow',15)}</button></div>
<div class="score">${icon('star',18)} <b id="stars">0</b><span>EXPLORER POINTS</span><i></i><b id="hud-count">0 / 9</b><span>DISCOVERED</span></div>
<div class="opening"><div class="eyebrow">A BIOLOGY ADVENTURE</div><h1>Big secrets.<br><em>Tiny world.</em></h1><p>Join Dr. Maya and four curious students.<br>Walk the streets. Meet the organelles.<br>Discover what keeps this city alive.</p><div class="cast-line"><i style="--cast:#eee8cf"></i><i style="--cast:#dc8f76"></i><i style="--cast:#75abb4"></i><i style="--cast:#a68dbd"></i><i style="--cast:#d6af61"></i><span>ONE CLASS. ONE INCREDIBLE JOURNEY.</span></div></div>
<div class="chapter-banner" id="chapter-banner"></div><button class="interact-prompt" id="interact" hidden><kbd>E</kbd><span>Talk with your class</span></button>
<div class="world-tools"><button id="zoom-in" aria-label="Move camera closer">+</button><button id="zoom-out" aria-label="Move camera farther">−</button><button id="reset-view" aria-label="Return to follow camera">${icon('compass',19)}</button></div>
<div id="challenge" class="challenge" hidden></div>
<div class="dialogue"><div class="speaker-portrait" id="portrait">M<span></span></div><div class="dialogue-copy"><div class="speaker" id="speaker">DR. MAYA <span>YOUR SCIENCE GUIDE</span></div><p id="dialogue-text">“Today, we’re going somewhere you’ve never been before. Come along — the class is waiting!”</p><div class="story-dots" id="story-dots"></div></div><button id="next" class="primary">${state.done?'Continue field trip':'Begin field trip'} ${icon('arrow',19)}</button></div>
<div class="controls-help"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> / arrows <b>Walk</b></span><span>Drag <b>Look around</b></span><span><kbd>Shift</kbd> Jog</span><span><kbd>E</kbd> Interact</span></div>
<div class="minimap"><div class="minimap-title">CELL CITY <span>N</span></div><svg viewBox="0 0 160 148" aria-label="Your position in Cell City"><ellipse cx="80" cy="69" rx="70" ry="58" fill="#557557" fill-opacity=".5" stroke="#c6d7b0" stroke-opacity=".5"/><path d="M80 138 80 120 42 106 32 91 26 58 63 40 98 36 129 50 124 95 99 106 80 87 80 69" fill="none" stroke="#dbcda5" stroke-width="3" stroke-opacity=".5"/>${stops.map((x,i)=>`<circle class="map-stop" data-map-stop="${i}" cx="${80+x.x*5.5}" cy="${i===0?128:69+x.z*5}" r="4" fill="#c3d1a5"/>`).join('')}<circle id="player-dot" cx="80" cy="139" r="4" fill="#fff2b0" stroke="#fff" stroke-width="1.5"/></svg><div class="minimap-caption">${icon('compass',12)} YOU & YOUR CLASS</div></div>
<div class="touch-controls" aria-label="Touch movement"><button data-move="KeyW" aria-label="Walk forward">↑</button><div><button data-move="KeyA" aria-label="Walk left">←</button><button data-move="KeyS" aria-label="Walk backward">↓</button><button data-move="KeyD" aria-label="Walk right">→</button></div></div>
</section></main><div id="modal" class="modal" hidden></div><div id="toast" role="status" aria-live="polite"></div>`;
const city=createCity($('#world'),$('#labels'),stops,{arrive:arriveAtStop,select:visit,status:updateStatus,mode:onMode,blocked:()=>notify('The route is blocked. Use the movement keys to reach an open path, then follow the teacher again.')});
city.setPaused(true);
function onMode(mode){document.body.classList.toggle('guided',mode==='guided');if(mode==='map'){mapOpen=true;$('.sidebar').hidden=false;}else{mapOpen=false;$('.sidebar').hidden=true;}}
function updateStatus(status){lastStatus=status;nearby=status.near;$('#player-dot').setAttribute('cx',80+status.x*2.2);$('#player-dot').setAttribute('cy',69+status.z*2.05);if(challenge==='travel'||challenge==='explore')$('#travel-status').textContent=`${status.guided?'Walking with Dr. Maya':'Exploring with your class'} · ${Math.round(status.distance)} m to destination`;$('#interact').hidden=!started||!['travel','explore'].includes(challenge)||nearby<0||nearby>state.done;if(!$('#interact').hidden)$('#interact span').textContent=`Meet ${stops[nearby].name}`;}
function showSpeaker(key,text){const person=cast[key]||cast.teacher;$('.speaker-portrait').style.setProperty('--speaker',person.color);$('#portrait').firstChild.textContent=key==='organelle'?'✦':person.name.split(' ').at(-1)[0];$('#speaker').innerHTML=`${key==='organelle'?stops[active].name:person.name}<span>${person.role}</span>`;city.setSpeaker(key);say(text,true);}
function playStory(lines,complete){challenge='story';storyLines=lines;storyIndex=0;storyComplete=complete;city.setStory(true);city.setPaused(false);$('#challenge').hidden=true;$('#next').hidden=false;$('#guide').hidden=true;document.body.classList.add('in-story');showStoryLine();}
function showStoryLine(){const [key,text]=storyLines[storyIndex];showSpeaker(key,text);$('#story-dots').innerHTML=storyLines.map((_,i)=>`<i class="${i<=storyIndex?'read':''}"></i>`).join('');$('#next').innerHTML=`${storyIndex===storyLines.length-1?'Let’s do it':'Continue'} ${icon('arrow',18)}`;}
function advanceStory(){if(storyIndex<storyLines.length-1){storyIndex++;showStoryLine();}else{$('#story-dots').innerHTML='';document.body.classList.remove('in-story');storyComplete?.();}}
function arriveAtStop(i){if(!started||!['travel','explore'].includes(challenge)||i>state.done)return;active=i;selected=[];step=0;mistakes=0;renderJourney();$('#destination').textContent=stops[i].place;$('#objective-kicker').textContent=`DISCOVERY ${String(i+1).padStart(2,'0')} / 09`;$('#travel-status').textContent='Stop, look, listen — then help the city.';$('#chapter-banner').innerHTML=`<span>DISCOVERY ${String(i+1).padStart(2,'0')}</span>${stops[i].place}`;$('#chapter-banner').classList.add('show');setTimeout(()=>$('#chapter-banner').classList.remove('show'),3500);playStory(conversations[i],()=>{challenge='mission';$('#next').hidden=true;renderChallenge();});}
function save(){try{localStorage.setItem('cell-city-v1',JSON.stringify(state));}catch{}renderJourney();}
function renderJourney(){
 $('#journey').innerHTML=stops.map((s,i)=>`<button class="stop ${i===active?'current':''} ${i<state.done?'complete':''}" data-stop="${i}" ${i>state.done?'disabled':''}><span class="stop-icon" style="--stop-color:${s.color}">${icon(i<state.done?'check':s.icon,18)}</span><span><strong>${s.name}</strong><small>${s.place}</small></span><span class="stop-number">${i<state.done?'✓':String(i+1).padStart(2,'0')}</span></button>`).join('');
 document.querySelectorAll('[data-stop]').forEach(b=>b.onclick=()=>visit(Number(b.dataset.stop)));$('#progress-text').textContent=`${state.done} / 9`;$('#progress-bar').style.width=`${state.done/9*100}%`;$('#stars').textContent=state.stars;$('#journal-count').textContent=state.done;$('#hud-count').textContent=`${state.done} / 9`;document.querySelectorAll('[data-map-stop]').forEach((el,i)=>el.setAttribute('fill',i<state.done?'#f4da92':i===active?'#ffffff':'#9ebc92'));city.setProgress(state.done,active);
}
function speak(text){if(sound&&'speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.92;speechSynthesis.speak(u);}}
function say(text,keepSpeaker=false){if(!keepSpeaker){$('#speaker').innerHTML='Dr. Maya<span>YOUR SCIENCE GUIDE</span>';$('#portrait').firstChild.textContent='M';$('#portrait').style.setProperty('--speaker',cast.teacher.color);city.setSpeaker('teacher');}$('#dialogue-text').textContent=`“${text}”`;speak(text);}
function notify(text){$('#toast').textContent=text;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600);}
function visit(i){if(['emergency','final','reveal'].includes(challenge))return notify('Finish saving the city first.');if(i>state.done)return notify('Discover the earlier stops before this chapter.');active=i;started=true;challenge='travel';document.body.classList.add('playing');document.body.classList.remove('in-story','has-challenge');$('.opening').hidden=true;$('#challenge').hidden=true;$('#next').hidden=true;$('#guide').hidden=false;$('#story-dots').innerHTML='';$('#destination').textContent=stops[i].place;$('#objective-kicker').textContent=`WALK TO DISCOVERY ${String(i+1).padStart(2,'0')}`;showSpeaker('teacher',travelLines[i]);renderJourney();city.setStory(false);city.setPaused(false);city.travel(i);}
function cardTop(kicker,title){return `<div class="challenge-top"><span class="eyebrow">${kicker}</span><button class="icon-button" id="close-challenge" aria-label="Close challenge">${icon('close',17)}</button></div><h3>${title}</h3>`;}
function renderChallenge(){const s=stops[active],box=$('#challenge');document.body.classList.add('has-challenge');box.hidden=false;box.innerHTML=cardTop(`DISCOVERY ${String(active+1).padStart(2,'0')} / 09`,s.heading)+`<p>${s.prompt}</p><div class="task-area"></div><div class="feedback" role="status" aria-live="polite"></div>`;$('#close-challenge').onclick=()=>{box.hidden=true;document.body.classList.remove('has-challenge');challenge='explore';city.setStory(false);$('#next').hidden=true;$('#guide').hidden=false;showSpeaker('teacher','Take a look around. Return to our meeting point and press E when you’re ready.');};const area=$('.task-area');
 if(s.type==='gate'){area.innerHTML=`<div class="item-display"><span>${['💧','🍎','☠','💨'][step]}</span><b>${s.items[step]}</b><small>Visitor ${step+1} of 4</small></div><div class="two-actions"><button class="choice" data-gate="0">Keep out</button><button class="choice positive" data-gate="1">Let in ${icon('arrow',16)}</button></div>`;document.querySelectorAll('[data-gate]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.gate)===s.answers[step],()=>{step++;step===s.items.length?win():renderChallenge();}));}
 if(s.type==='select'){area.innerHTML=`<div class="choices">${s.items.map((it,i)=>`<button class="choice ${selected.includes(i)?'selected':''}" data-choice="${i}"><span class="choice-dot">${selected.includes(i)?'✓':'+'}</span>${it}</button>`).join('')}</div><button id="check" class="primary wide">Check answer ${icon('check',18)}</button>`;document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const i=+b.dataset.choice;selected=selected.includes(i)?selected.filter(x=>x!==i):[...selected,i];renderChallenge();});$('#check').onclick=()=>answer(selected.length===s.answers.length&&selected.every(i=>s.answers.includes(i)),win);}
 if(s.type==='sort'){area.innerHTML=`<div class="item-display"><span>📦</span><b>${s.items[step]}</b><small>Package ${step+1} of ${s.items.length}</small></div><div class="choices">${s.choices.map((it,i)=>`<button class="choice" data-choice="${i}">${icon('box',18)}${it}</button>`).join('')}</div>`;document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>answer(+b.dataset.choice===s.answers[step],()=>{step++;step===s.items.length?win():renderChallenge();}));}
 if(s.type==='sequence'){area.innerHTML=`<div class="sequence-track">${s.answers.map((_,i)=>`<span class="${i<step?'filled':''}">${i<step?'✓':i+1}</span>${i<2?'<i>→</i>':''}`).join('')}</div><div class="choices">${s.items.map((it,i)=>`<button class="choice" data-choice="${i}" ${s.answers.slice(0,step).includes(i)?'disabled':''}>${it}${icon('arrow',16)}</button>`).join('')}</div>`;document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>answer(+b.dataset.choice===s.answers[step],()=>{step++;step===s.items.length?win():renderChallenge();}));}}
function answer(correct,fn){if(correct){tone();if(challenge==='mission')city.demonstrate(active,step);fn();}else{mistakes++;$('.feedback').textContent='Almost! Think about this organelle’s job and try again.';$('.feedback').classList.add('error');tone(false);}}
function tone(good=true){if(!sound)return;try{const c=new (window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=good?660:220;g.gain.setValueAtTime(.07,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.2);o.start();o.stop(c.currentTime+.2);o.onended=()=>c.close();}catch{}}
function win(){const fresh=active===state.done;if(fresh){state.done++;state.stars+=Math.max(10,30-mistakes*5);save();}challenge='won';city.celebrate();city.repair(active);$('#challenge').innerHTML=`<div class="success-icon">${icon('check',30)}</div><div class="eyebrow">DISCOVERY COMPLETE</div><h3>${stops[active].name}, discovered.</h3><p>${stops[active].fact}</p><div class="fact-chip">${icon('book',17)} Added to your field journal</div><button id="continue" class="primary wide">${active===8?'Enter the control room':'Next destination'} ${icon('arrow',18)}</button>`;say(active===8?'Every department is working together. Wait… an alarm! Cell City needs your help!':'Excellent discovery! Follow me to our next stop.');$('#continue').onclick=()=>active===8?startEmergency():visit(active+1);}
function startEmergency(){challenge='emergency';step=0;mistakes=0;city.setStory(true);city.setEmergency(true);$('#next').hidden=true;$('#challenge').hidden=false;document.body.classList.add('playing');say('System failure! Use what you discovered to send help to the right department.');renderEmergency();}
function renderEmergency(){const [problem,correct,index]=emergencies[step];$('#challenge').innerHTML=`<div class="alarm">${icon('bolt',18)} CELL CITY NEEDS YOU</div><h3>${problem}</h3><p>Which organelle can solve this problem?</p><div class="rescue-progress">${emergencies.map((_,i)=>`<i class="${i<step?'done':''}"></i>`).join('')}</div><div class="choices">${[index,(index+3)%9,(index+6)%9].sort((a,b)=>a-b).map(i=>`<button class="choice" data-rescue="${i}">${icon(stops[i].icon,18)}${stops[i].name}</button>`).join('')}</div><div class="feedback" role="status" aria-live="polite"></div>`;document.querySelectorAll('[data-rescue]').forEach(b=>b.onclick=()=>answer(+b.dataset.rescue===index,()=>{step++;city.repair(index);city.celebrate();if(step===emergencies.length){if(!state.rescued)state.stars+=60;state.rescued=true;save();reveal();}else renderEmergency();}));}
function reveal(){playStory([['teacher','So, explorers… what did you discover?'],['aria','The cell is like a city!'],['ben','Every organelle has a different job.'],['zoya','And they all work together!'],['teacher','Exactly. A cell is an organized system. Its parts work together to maintain life.'],['leo','Wait… we were inside a CELL?!'],['teacher','Welcome to the microscopic world!']],showRevealCard);city.reveal();}
function showRevealCard(){challenge='reveal';$('#next').hidden=true;$('#challenge').hidden=false;$('#objective-kicker').textContent='THE FINAL REVELATION';$('#destination').textContent='You were inside a cell all along';$('#travel-status').textContent='Every part works together to maintain life.';say('You were inside a CELL all along! Every part has a special role, and together they keep the cell alive. Welcome to the microscopic world!');$('#challenge').innerHTML=`<div class="success-icon">${icon('dna',30)}</div><div class="eyebrow">THE SECRET IS OUT</div><h3>A whole world.<br>Inside a single cell.</h3><p>You saved Cell City! These buildings represent organelles working together in a living cell.</p><p class="science-note">Our city combines plant and animal examples. Real plant cells have a cell wall and chloroplasts; their lytic vacuoles do much of the recycling shown here as lysosomes.</p><button class="primary wide" id="final-start">One last challenge ${icon('arrow',18)}</button>`;$('#final-start').onclick=()=>{challenge='final';step=0;renderFinal();};}
const jobs=['Controls entry and exit','Carries out photosynthesis','Modifies, sorts and packages','Synthesis and transport network','Builds proteins','Produces ATP for cellular work','Stores substances; maintains turgor','Digests unwanted cellular materials','Contains genetic instructions'];
function renderFinal(){const index=(step*4)%9;$('#challenge').innerHTML=`<div class="eyebrow">FINAL MATCH · ${step+1} / 9</div><h3>Who does this job?</h3><div class="job-card">${jobs[index]}</div><div class="choices">${[index,(index+2)%9,(index+5)%9].sort((a,b)=>a-b).map(i=>`<button class="choice" data-match="${i}">${icon(stops[i].icon,18)}${stops[i].name}</button>`).join('')}</div><div class="feedback" role="status" aria-live="polite"></div>`;document.querySelectorAll('[data-match]').forEach(b=>b.onclick=()=>answer(+b.dataset.match===index,()=>{step++;if(step===9){if(!state.finished)state.stars+=90;state.finished=true;save();finish();}else renderFinal();}));}
function finish(){challenge='finished';city.reveal();city.celebrate();$('#challenge').innerHTML=`<div class="success-icon trophy">${icon('star',34)}</div><div class="eyebrow">MISSION COMPLETE</div><h3>Official Cell City explorer.</h3><p>Nine discoveries. One city saved. You know how organelles work together to maintain life.</p><div class="final-stats"><b>${state.stars}<small>EXPLORER POINTS</small></b><b>9 / 9<small>DISCOVERIES</small></b></div><button class="primary wide" id="review-journal">View your field journal ${icon('book',18)}</button><button class="text-button" id="free-roam">Return to the city and explore</button><button class="text-button" id="replay">Start a new expedition</button>`;$('#review-journal').onclick=openJournal;$('#replay').onclick=resetPrompt;$('#free-roam').onclick=()=>{city.reset();renderJourney();started=true;challenge='explore';document.body.classList.remove('in-story','has-challenge');$('#challenge').hidden=true;$('#next').hidden=true;$('#guide').hidden=false;city.setStory(false);city.setPaused(false);$('#objective-kicker').textContent='FREE EXPLORATION';$('#destination').textContent='Your city. Your discoveries.';showSpeaker('teacher','The whole city is open! Walk with your class and press E at any discovered stop to revisit its story.');};say('Wonderful work, explorers. The smallest things can hold the biggest secrets. Keep asking questions!');}
function openModal(html){city.setPaused(true);if(sound&&'speechSynthesis'in window)speechSynthesis.pause();modalReturn=document.activeElement;$('#modal').innerHTML=`<section class="modal-card" role="dialog" aria-modal="true" aria-labelledby="modal-title">${html}</section>`;$('#modal').hidden=false;$('#modal').querySelector('button')?.focus();}
function closeModal(){$('#modal').hidden=true;city.setPaused(!started);if(sound&&'speechSynthesis'in window)speechSynthesis.resume();modalReturn?.focus();}
function openJournal(){openModal(`<div class="journal-header"><div><span class="eyebrow">YOUR EXPEDITION NOTES</span><h2 id="modal-title">Field journal <em>${state.done} / 9</em></h2></div><button id="close-modal" class="icon-button" aria-label="Close journal">${icon('close')}</button></div><p>Meet the tiny teams that keep cells alive.</p><div class="journal-grid">${stops.map((s,i)=>`<article class="journal-entry ${i>=state.done?'undiscovered':''}"><span class="journal-symbol" style="color:${s.color}">${icon(i<state.done?s.icon:'compass',25)}</span><div><small>${String(i+1).padStart(2,'0')} · ${s.place}</small><h3>${s.name}</h3><p>${i<state.done?s.fact:'Visit this stop to unlock your notes.'}</p></div></article>`).join('')}</div><div class="journal-bottom"><p>City structures are analogies, not literal cell anatomy.</p><button class="text-button" id="reset-progress">Reset progress</button></div>`);$('#close-modal').onclick=closeModal;$('#reset-progress').onclick=resetPrompt;}
function resetPrompt(){openModal(`<h2 id="modal-title">Start a new expedition?</h2><p>This clears your discoveries and points on this device.</p><div class="two-actions"><button class="choice" id="cancel-reset">Keep exploring</button><button class="primary" id="confirm-reset">Start fresh</button></div>`);$('#cancel-reset').onclick=closeModal;$('#confirm-reset').onclick=()=>{state={done:0,stars:0,rescued:false,finished:false};active=0;city.reset();save();closeModal();started=false;beginFieldTrip();};}
function beginFieldTrip(){started=true;$('.opening').hidden=true;document.body.classList.add('playing');city.setPaused(false);if(state.finished){$('#challenge').hidden=false;$('#next').hidden=true;finish();}else if(state.done===9)startEmergency();else if(state.done>0)visit(active);else playStory(prologue,()=>visit(0));}
$('#next').onclick=()=>{if(!started)beginFieldTrip();else if(challenge==='story')advanceStory();else if(challenge==='mission')renderChallenge();};
$('#guide').onclick=()=>visit(active);$('#interact').onclick=()=>city.interact();
$('#journal').onclick=openJournal;$('#explore').onclick=()=>{if(!started)return notify('Begin the field trip to open your city map.');city.overview();};$('#close-map').onclick=()=>{city.follow();onMode('follow');};$('.brand').onclick=e=>{e.preventDefault();city.follow();onMode('follow');};
$('#sound').onclick=()=>{sound=!sound;$('#sound').classList.toggle('enabled',sound);$('#sound').setAttribute('aria-label',sound?'Turn narration off':'Turn narration on');if(!('speechSynthesis'in window)){sound=false;notify('Spoken narration is unavailable in this browser.');}else if(sound)speak($('#dialogue-text').textContent);else speechSynthesis.cancel();};
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{notify('Fullscreen is unavailable here. Open the game in a browser tab.');}};
$('#zoom-in').onclick=()=>city.zoom(.86);$('#zoom-out').onclick=()=>city.zoom(1.16);$('#reset-view').onclick=()=>{city.follow();onMode('follow');};$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal();};
for(const b of document.querySelectorAll('[data-move]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);city.setInput(b.dataset.move,true);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>city.setInput(b.dataset.move,false));}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#modal').hidden)closeModal();else if(challenge==='mission')$('#close-challenge')?.click();else if(mapOpen){city.follow();onMode('follow');}}if(e.code==='KeyE'&&!e.defaultPrevented&&challenge==='story'&&!e.repeat&&$('#modal').hidden){e.preventDefault();advanceStory();}if(e.key==='Tab'&&!$('#modal').hidden){const list=[...$('#modal').querySelectorAll('button,a,input,[tabindex="0"]')];if(e.shiftKey&&document.activeElement===list[0]){e.preventDefault();list.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===list.at(-1)){e.preventDefault();list[0]?.focus();}}});renderJourney();
